name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Set a branch name to trigger deployment
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci
          if [ $? -ne 0 ]; then
            echo "npm ci failed"
            exit 1
          fi

      - name: List files
        run: ls -R
        
      - name: Build
        run: |
          npm run build
          if [ $? -ne 0 ]; then
            echo "Build failed"
            echo "Package.json contents:"
            cat package.json
            echo "Vite config contents:"
            cat vite.config.js
            exit 1
          fi

      - name: List dist folder
        run: |
          if [ -d "dist" ]; then
            ls -R dist
          else
            echo "dist folder does not exist"
            exit 1
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
