name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Debug - Environment Info
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          echo "Dependencies installed."
          npm list --depth=0

      - name: Build
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build process completed."

      - name: Debug - Build Output
        run: |
          echo "Build output:"
          ls -R dist || echo "dist directory not found"

      - name: Prepare for deployment
        run: |
          echo "Preparing for deployment..."
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          echo "Git config set."

      - name: Deploy to GitHub Pages
        run: |
          echo "Starting deployment..."
          git checkout --orphan gh-pages
          git rm -rf .
          echo "Moving build files..."
          mv dist/* . || echo "Failed to move dist contents"
          rm -rf dist
          echo "Adding files to git..."
          git add .
          echo "Committing changes..."
          git commit -m "Deploy to GitHub Pages" || echo "Nothing to commit"
          echo "Pushing to gh-pages branch..."
          git push -f origin gh-pages || echo "Failed to push to gh-pages"
          echo "Deployment steps completed."

      - name: Debug - Final State
        if: always()
        run: |
          echo "Final repository state:"
          git status
          echo "Recent git log:"
          git log -n 5
          echo "Current directory contents:"
          ls -la

      - name: Upload error logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: |
            ./*.log
            ./npm-debug.log*
            ./yarn-debug.log*
            ./yarn-error.log*
