name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        continue-on-error: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
        continue-on-error: true

      - name: Print Node.js and npm version
        run: |
          node --version
          npm --version
        continue-on-error: true

      - name: List repository contents
        run: ls -la
        continue-on-error: true

      - name: Print package.json contents
        run: cat package.json
        continue-on-error: true

      - name: Print vite.config.js contents
        run: cat vite.config.js
        continue-on-error: true

      - name: Install dependencies
        run: |
          npm ci
          npm ls --depth=0
        continue-on-error: true

      - name: Build
        run: npm run build
        continue-on-error: true

      - name: List dist folder
        run: |
          if [ -d "dist" ]; then
            ls -R dist
          else
            echo "dist folder does not exist"
            exit 1
          fi
        continue-on-error: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
        continue-on-error: true

      - name: Check deployment
        if: failure()
        run: |
          echo "Deployment failed"
          git status
          git log -n 5
