name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Print Node.js and npm version
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: List installed packages
        run: npm ls --depth=0

      - name: Print package.json contents
        run: cat package.json

      - name: Print vite.config.js contents
        run: cat vite.config.js || echo "vite.config.js not found"

      - name: Build
        run: npm run build

      - name: List dist folder
        run: |
          if [ -d "dist" ]; then
            ls -R dist
          else
            echo "dist folder does not exist"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git checkout --orphan gh-pages
          git rm -rf .
          mv dist/* .
          rm -rf dist
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages

      - name: Check deployment
        if: failure()
        run: |
          echo "Deployment failed"
          git status
          git log -n 5
          echo "Contents of current directory:"
          ls -R
          echo "Node.js version:"
          node --version
          echo "npm version:"
          npm --version
          echo "package.json contents:"
          cat package.json
          echo "vite.config.js contents:"
          cat vite.config.js || echo "vite.config.js not found"
