name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Debug - Environment Info
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la

      - name: Install dependencies
        run: |
          npm ci
        continue-on-error: true

      - name: Build
        run: |
          npm run build
        continue-on-error: true

      - name: Debug - Build Output
        run: |
          echo "Build output:"
          ls -R dist || echo "dist directory not found"

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git checkout --orphan gh-pages
          git rm -rf .
          mv dist/* . || echo "Failed to move dist contents"
          rm -rf dist
          git add .
          git commit -m "Deploy to GitHub Pages" || echo "Nothing to commit"
          git push -f origin gh-pages || echo "Failed to push to gh-pages"
        continue-on-error: true

      - name: Debug - Final State
        if: always()
        run: |
          echo "Final repository state:"
          git status
          echo "Recent git log:"
          git log -n 5
          echo "Current directory contents:"
          ls -la
          echo "npm logs:"
          ls -la ~/.npm/_logs || echo "No npm logs found"

      - name: Capture Logs
        if: always()
        run: |
          mkdir -p logs
          cp ~/.npm/_logs/* logs/ || echo "No npm logs to copy"
          npm run build > logs/build.log 2>&1 || echo "Build command failed"
          git status > logs/git-status.log 2>&1
          git log -n 10 > logs/git-log.log 2>&1

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deployment-logs
          path: |
            logs
            ~/.npm/_logs
